openapi: 3.0.0
info:
  title: Autobarn API
  description: |
    The Autobarn API, as used in Dylan Beattie's workshop
    [Introduction to Distributed Systems with .NET](https://urs.tl/dsnet).

    (Yep, your description can have multiple lines and contain Markdown! Cool!)
  version: 1.0.0
servers:
  - url: /api
paths:
  /vehicles:
    get:
      tags:
        - Vehicles
      summary: Returns a list of vehicles.
      description: Returns a list of all the vehicles available in the Autobarn database
      responses:
        '200':    # status code
          description: A JSON array of vehicle objects
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
  /vehicles/{registration}:
    put:
      summary: Create or update a vehicle
      consumes:
        - application/json
      parameters:
        - $ref: '#/components/parameters/registration'
        - in: body
          name: vehicle
          description: The details of the vehicle to create or update
          schema:
            $ref: '#/components/schemas/Vehicle'
      responses:
        200:
          description: OK.
        201:
          description: Created.
    get:
      tags:
        - Vehicles
      parameters:
        - $ref: '#/components/parameters/registration'
      responses:
        '404':
          description: There is no vehicle in the system matching that registration
        '200':    # status code
          description: A vehicle object
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Vehicle'

components:
  parameters:
    registration:
    - in: path
      name: registration
      schema:
        type: string
      required: true
      description: The registration plate of the vehicle you want to get
  schemas:
    Vehicle:
      type: object   # Data type
      properties: 
        registration:
          type: string
        modelCode:
          type: string
        color: 
          type: string
        year:
          type: integer
      example:
        registration: OUTATIME
        modelCode: dmc-delorean
        color: Silver
        year: 1985
